"""
Generate Kurmanji pronunciation clips with Meta MMS TTS (facebook/mms-tts-kmr)
and emit src/data/wordAudio.ts mapping each word to its bundled mp3.

Run:  python scripts/generate_word_audio.py
Deps: torch (CPU), transformers, scipy, numpy, imageio-ffmpeg

Re-runnable: existing mp3s are skipped, so you can stop/resume.
"""
import re
import sys
import subprocess
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VOCAB = ROOT / "src" / "data" / "vocabulary.ts"
OUT_DIR = ROOT / "assets" / "audio" / "words"
MAP_TS = ROOT / "src" / "data" / "wordAudio.ts"
MODEL_ID = "facebook/mms-tts-kmr-script_latin"

OUT_DIR.mkdir(parents=True, exist_ok=True)


def parse_vocab():
    text = VOCAB.read_text(encoding="utf-8")
    # id: 'v001', wordKu: 'silav'  (Kurmanji words contain no apostrophes)
    pairs = re.findall(r"id:\s*'(v\d+)',\s*wordKu:\s*'([^']*)'", text)
    # de-dupe by id, keep order
    seen = set()
    out = []
    for vid, word in pairs:
        if vid in seen:
            continue
        seen.add(vid)
        out.append((vid, word))
    return out


def main():
    pairs = parse_vocab()
    print(f"Parsed {len(pairs)} vocabulary words from {VOCAB.name}")
    if not pairs:
        sys.exit("No words parsed — check the regex / vocab format.")

    import numpy as np
    import torch
    import scipy.io.wavfile
    import imageio_ffmpeg
    from transformers import VitsModel, AutoTokenizer

    ffmpeg = imageio_ffmpeg.get_ffmpeg_exe()
    print("ffmpeg:", ffmpeg)

    print(f"Loading {MODEL_ID} (first run downloads ~150 MB) ...")
    model = VitsModel.from_pretrained(MODEL_ID)
    tok = AutoTokenizer.from_pretrained(MODEL_ID)
    model.eval()
    sr = model.config.sampling_rate
    print(f"Model ready. sampling_rate={sr}, is_uroman={getattr(tok, 'is_uroman', 'n/a')}")

    mapping = {}
    failures = []
    tmp_wav = OUT_DIR / "_tmp.wav"

    for i, (vid, word) in enumerate(pairs):
        mp3 = OUT_DIR / f"{vid}.mp3"
        key = unicodedata.normalize("NFC", word).lower().strip()
        mapping[key] = vid
        if mp3.exists():
            continue
        try:
            inputs = tok(word, return_tensors="pt")
            with torch.no_grad():
                wav = model(**inputs).waveform
            data = wav.squeeze().cpu().numpy().astype("float32")
            peak = float(np.abs(data).max()) or 1.0
            int16 = (data / peak * 32767 * 0.95).astype("int16")
            scipy.io.wavfile.write(str(tmp_wav), sr, int16)
            subprocess.run(
                [ffmpeg, "-y", "-i", str(tmp_wav), "-ac", "1", "-ar", "22050",
                 "-b:a", "48k", str(mp3)],
                check=True, capture_output=True,
            )
        except Exception as e:  # noqa: BLE001
            failures.append((vid, word, str(e)[:120]))
            mapping.pop(key, None)
        if i % 20 == 0:
            print(f"  {i}/{len(pairs)} ...")

    if tmp_wav.exists():
        tmp_wav.unlink()

    # Emit the TypeScript map
    lines = [
        "// AUTO-GENERATED by scripts/generate_word_audio.py — do not edit by hand.",
        "// Bundled Kurmanji pronunciation clips (Meta MMS, facebook/mms-tts-kmr).",
        "// Key = wordKu.normalize('NFC').toLowerCase().trim()",
        "export const WORD_AUDIO: Record<string, number> = {",
    ]
    for key, vid in sorted(mapping.items()):
        esc = key.replace("\\", "\\\\").replace("'", "\\'")
        lines.append(f"  '{esc}': require('../../assets/audio/words/{vid}.mp3'),")
    lines.append("};")
    lines.append("")
    MAP_TS.write_text("\n".join(lines), encoding="utf-8")

    print(f"\nDone. {len(mapping)} clips mapped -> {MAP_TS}")
    total = sum(f.stat().st_size for f in OUT_DIR.glob('*.mp3'))
    print(f"Bundled audio size: {total/1024/1024:.2f} MB across {len(list(OUT_DIR.glob('*.mp3')))} files")
    if failures:
        print(f"\n{len(failures)} FAILED:")
        for vid, word, err in failures[:20]:
            print(f"  {vid} '{word}': {err}")


if __name__ == "__main__":
    main()
